.TH MANGO-LASSI 1 "May 20, 2010"
.SH NAME
mango-lassi \- Share mouse and pointer with other computers.
.SH SYNOPSIS
.B mango-lassi
.RI [ OPTIONS ] ...
.BR
.SH DESCRIPTION
This manual page documents briefly the
.B mango-lassi
command-line options.
.PP
.B mango-lassi
lets you to share mouse and pointer with other computers using Avahi.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help options.
.TP
.B \-\-help\-all
Show all help options.
.TP
.B \-\-help\-gtk
Show GTK+ Options.
.TP
.B \-\-class=CLASS
Program class as used by the window manager.
.TP
.B \-\-name=NAME
Program name as used by the window manager.
.TP
.B \-\-screen=SCREEN
X screen to use.
.TP
.B \-\-sync
Make X calls synchronous.
.TP
.B \-\-gtk\-module=MODULES
Load additional GTK+ modules.
.TP
.B \-\-g\-fatal\-warnings
Make all warnings fatal.
.TP
.B \-v, \-\-verbose
Display information useful for debugging.
.TP
.B \-\-display=DISPLAY
X display to use.
.SH AUTHOR
mango-lassi was written by Lennart Poettering <mzjro@0pointer.net>.
Sven Herzberg did a friendly fork (as in: he asked Lennart) and continues to
maintain mango-lassi.
.SH SEE ALSO
Homepage: http://github.com/herzi/mango-lassi/
.PP
This manual page was written by Kartik Mistry <kartik@debian.org>,
for the Debian project (and may be used by others).
